### PR TITLE
Added a way to get steam inventory data via the steam api.

### PR DESCRIPTION
**Pull request by Tvde1**

### CODE REVIEW

**Comment by MihajloNesic** [comment]
So I added my steam api key (the one declared above is the backpack.tf key) and changed the zeros to my steam profile id (76561198044606823) and it crashed when I started it.

I need a way of displaying items (for each item to show name, description, photo url, name and bg color)

**Comment by Tvde1** [comment]
I just realised that it's trying to use the backpack.tf key instead of the steam api key.

**Comment by MihajloNesic** [comment]
I have this
var steamInvData = new SteamInventoryData(apikeySTEAM);
var items = await steamInvData.GetItems(kresenkoid);

but it is not working

**Comment by MihajloNesic** [comment]
Ok, I set break point at the loop. The program successfully got the item count from my backpack, but it failed to print the item names

err3333

**Comment by Tvde1** [comment]
can you try merging this and pushing your steam id etc?

**Comment by MihajloNesic** [comment]
Merging what, the code? I am using your code (version of changed code)

**Comment by Tvde1** [comment]
If you merge this branch to master, you can commit the edits you made and I can check it out and fix it again.

**Comment by MihajloNesic** [comment]
Ok, done. Sorry, I'm still so unfamiliar with Github

**Pull request merged**
